name: Deploy ML Training Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  deploy-staging:
    uses: viam-modules/common-workflows/.github/workflows/deploy_training_script.yaml@main
    with:
      framework: tflite
      script_name: detection-tflite
      model_type: object_detection
    secrets: inherit
